app/views/main_views.py
from flask import Blueprint, url_for, render_template
from werkzeug.utils import redirect
from app.models import Site, Point, Data
from app.views.user_views import login_required

bp = Blueprint('main', __name__, url_prefix='/')

@bp.route('/hello')
def hello_daon():
    return '다온에 오신것을 환영합니다!!'

@bp.route('/')
@login_required
def index():
    site = Site.query.get_or_404(1)

    from app.defines import point_types_total
    point_types_total = point_types_total()
    point_now = len(Point.query.all())
    point_per = point_now / point_types_total * 100
    point_progress = [point_types_total, point_now, point_per]

    cost_total = site.cost
    cost_now = site.endcost
    cost_per = cost_now / cost_total * 100
    cost_progress = [cost_total, cost_now, cost_per]

    if point_now > 8:
        point_list = Point.query.order_by(Point.cst18.desc())[0:8]
    else:
        point_list = Point.query.order_by(Point.cst18.desc())

    point = Point.query.get_or_404(point_list[0].id)
    data_list = Data.query.filter_by(point_id=point.id).order_by(Data.measuringdate)
    data_list_ea = Data.query.filter_by(point_id=point.id).order_by(Data.measuringdate).count()

    return render_template('main/main_dashboard.html', site=site, point_list=point_list, point=point, \
                           data_list=data_list, data_list_ea=data_list_ea, \
                           point_progress=point_progress, cost_progress=cost_progress)

app/views/paper_views.py
from flask import Blueprint, render_template, request, url_for, g, flash
from werkzeug.utils import redirect
from datetime import datetime
import openpyxl

from app import db
from app.models import Site, Point, Data
from app.forms import PointForm
from app.views.user_views import login_required

bp = Blueprint('paper', __name__, url_prefix='/paper')

@bp.route('/week/')
@login_required
def paper_week():
    point_list = Point.query.all()
    return render_template('paper/paper_week.html', point_list=point_list)

@bp.route('/print_data/<int:point_id>, how_page, from_dateg, to_dateg')
@login_required
def data_print(point_id):
    site = Site.query.get_or_404(1)
    point = Point.query.get_or_404(point_id)
    page_type = request.args.get('how_page')
    from_date = request.args.get('from_dateg')
    to_date = request.args.get('to_dateg')

    if from_date == "초기데이터" and to_date == "최종데이터":
        data_list = Data.query.filter_by(point_id=point_id).order_by(Data.measuringdate)
        data_list_ea = Data.query.filter_by(point_id=point_id).order_by(Data.measuringdate).count()
    elif from_date == "초기데이터":
        data_list = Data.query.filter_by(point_id=point_id).\
            filter(Data.measuringdate <= to_date).order_by(Data.measuringdate)
        data_list_ea = Data.query.filter_by(point_id=point_id).\
            filter(Data.measuringdate <= to_date).order_by(Data.measuringdate).count()
    elif to_date == "최종데이터":
        data_list = Data.query.filter_by(point_id=point_id).\
            filter(Data.measuringdate >= from_date).order_by(Data.measuringdate)
        data_list_ea = Data.query.filter_by(point_id=point_id).\
            filter(Data.measuringdate >= from_date).order_by(Data.measuringdate).count()
    else:
        data_list = Data.query.filter_by(point_id=point_id).\
            filter(Data.measuringdate >= from_date).\
            filter(Data.measuringdate <= to_date).\
            order_by(Data.measuringdate)
        data_list_ea = Data.query.filter_by(point_id=point_id).\
            filter(Data.measuringdate >= from_date).\
            filter(Data.measuringdate <= to_date).\
            order_by(Data.measuringdate).count()

    if data_list_ea != 0 :
        if point.type == "지중경사계":
            min_value = max_value = 0.0
            if data_list[-1]:
                for inclino in data_list[-1].data09.split(','):
                    if max_value < float(inclino): max_value = float(inclino)
                    if min_value > float(inclino): min_value = float(inclino)
                if abs(max_value) > abs(min_value):
                    point.cst16 = max_value
                else:
                    point.cst16 = min_value
                db.session.commit()
            return render_template('paper/data_print.html', point=point, site=site, data_list=data_list, \
                                   data_list_ea=data_list_ea, from_date=from_date, to_date=to_date)
        else:
            old_date = data_list[0].measuringdate
            old_termDisplacement = 0
            for data in data_list:
                data.data11 = (datetime.strptime(str(data.measuringdate), "%Y-%m-%d %H:%M:%S") - datetime.strptime(str(point.startdate), "%Y-%m-%d")).days
                data.data12 = (datetime.strptime(str(data.measuringdate), "%Y-%m-%d %H:%M:%S") - datetime.strptime(str(old_date), "%Y-%m-%d %H:%M:%S")).days

                if point.type == "지하수위계":
                    data.data13 = (data.data01 - data_list[0].data01)
                    if data.data12 != 0:
                        data.data14 = (data.data13 - old_termDisplacement) / data.data12
                    else:
                        data.data14 = 0

                if point.type == "하중계":
                    data.data04 = point.cst12*(point.cst13-(data.data01+data.data02+data.data03))

                if point.type == "지표침하계":
                    data.data13 = (data.data01 - data_list[0].data01) * 1000
                elif point.type == "하중계":
                    if Data.query.filter_by(point_id=point_id).count()  > 1:
                        data.data13 = float(data.data04 - data_list[0].data04)
                    else:
                        data.data13 = 0
                else:
                    data.data13 = (data.data01 - data_list[0].data01)

                if point.type == "변형률계":
                    data.data04 = data.data13/1000000 * point.cst11
                    data.data15 = data.data04 - old_termDisplacement
                    old_termDisplacement = data.data04
                else:
                    data.data15 = data.data13 - old_termDisplacement
                    old_termDisplacement = data.data13
                old_date = data.measuringdate
            db.session.commit()
            if point.type == "지하수위계": point.cst16 = data.data14
            else: point.cst16 = data.data13
            db.session.commit()
            return render_template('paper/data_print.html', point=point, site=site, data_list=data_list, \
                                   data_list_ea=data_list_ea, from_date=from_date, to_date=to_date, page_type=page_type)
    else:
        return render_template('paper/data_print.html', point=point, site=site, data_list=data_list,\
                               flowdate=0, data_list_ea=data_list_ea, \
                               from_date=from_date, to_date=to_date, page_type=page_type)

app/views/site_views.py
from flask import Blueprint, render_template, request, url_for, g, flash
from werkzeug.utils import redirect
from datetime import datetime


from .. import db
from app.models import Site, Point
from app.forms import SiteForm
from app.views.user_views import login_required

bp = Blueprint('site', __name__, url_prefix='/site')


@bp.route('/')
@login_required
def site_detail():
    site = Site.query.get_or_404(1)
    return render_template('site/site_detail.html', site=site)

@bp.route('/map')
@login_required
def site_map():
    site = Site.query.get_or_404(1)
    return render_template('site/site_map.html', site=site)

@bp.route('/modify/<int:site_id>', methods=('GET', 'POST'))
@login_required
def site_modify(site_id):
    site = Site.query.get_or_404(site_id)
    '''
    if g.user.power != "admin":
        flash('수정권한이 없습니다')
        return redirect(url_for('site.site_detail', site_id=site_id))
    '''
    if request.method == 'POST':
        form = SiteForm()
        if form.validate_on_submit():
            form.populate_obj(site)
            db.session.commit()
            return redirect(url_for('site.site_detail', site_id=site_id))
    else:
        form = SiteForm(obj=site)
    return render_template('site/site_form.html', form=form)

@bp.route('/volume')
@login_required
def site_volume():
    from app.defines import area_types, point_types
    area_types = area_types()
    point_types = point_types()
    site = Site.query.get_or_404(1)

    area_table = []
    for point_type,area_type in zip(point_types,area_types):
        for point_type2 in point_type:
            pointea = Point.query.filter(Point.area == area_type[0], Point.type == point_type2[0]).count()
            point_type2.append(pointea)
        area_table.append(len(point_type))

    return render_template('site/site_volume.html',
                           area_types = area_types, point_types = point_types,
                           site=site, area_table=area_table )

@bp.route('/frequency')
@login_required
def site_frequency():
    site = Site.query.get_or_404(1)
    return render_template('site/site_frequency.html', site=site)

@bp.route('/standard')
@login_required
def site_standard():
    site = Site.query.get_or_404(1)
    return render_template('site/site_standard.html', site=site)

@bp.route('/progress')
@login_required
def site_progress():
    site = Site.query.get_or_404(1)
    date_total = ((datetime.strptime(str(site.enddate), "%Y-%m-%d") - datetime.strptime(str(site.startdate), "%Y-%m-%d"))).days
    date_now = (datetime.now() - datetime.strptime(str(site.startdate), "%Y-%m-%d")).days
    dete_per = date_now / date_total * 100
    dete_progress = [date_total, date_now, dete_per]

    from app.defines import point_types_total
    point_types_total = point_types_total()
    point_now = len(Point.query.all())
    point_per = point_now / point_types_total * 100
    point_progress = [point_types_total, point_now, point_per]

    cost_total = site.cost
    cost_now = site.endcost
    cost_per = cost_now / cost_total * 100
    cost_progress = [cost_total, cost_now, cost_per]
    return render_template('site/site_progress.html', site=site, dete_progress=dete_progress,
                           point_progress=point_progress, cost_progress=cost_progress)

app/views/user_views.py
from flask import Blueprint, url_for, render_template, flash, request, session, g
from werkzeug.security import generate_password_hash, check_password_hash
from werkzeug.utils import redirect

from app import db
from app.forms import UserLoginForm, UserCreateForm, UserModifyForm
from app.models import User
import functools

bp = Blueprint('user', __name__, url_prefix='/user')

@bp.route('/signup/', methods=('GET', 'POST'))
def signup():
    form = UserCreateForm()
    if request.method == 'POST' and form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if not user:
            user = User(username=form.username.data,
                        password=generate_password_hash(form.password1.data),
                        truename = form.truename.data,
                        company=form.company.data,
                        phone=form.phone.data,
                        email=form.email.data,
                        power='wait')
            db.session.add(user)
            db.session.commit()
            return redirect(url_for('main.index'))
        else:
            flash('이미 존재하는 사용자입니다.')
    return render_template('user/signup.html', form=form)

@bp.route('/login/', methods=('GET', 'POST'))
def login():
    form = UserLoginForm()
    if request.method == 'POST' and form.validate_on_submit():
        error = None
        user = User.query.filter_by(username=form.username.data).first()
        if not user:
            error = "존재하지 않는 사용자입니다."
        elif not check_password_hash(user.password, form.password.data):
            error = "비밀번호가 올바르지 않습니다."
        elif user.power == "wait":
            error = "관리자의 사용 승인까지 기다려 주세요."
        if error is None:
            session.clear()
            session['user_id'] = user.id
            return redirect(url_for('main.index'))
        flash(error)
    return render_template('user/login.html', form=form)

@bp.before_app_request
def load_logged_in_user():
    user_id = session.get('user_id')
    if user_id is None:
        g.user = None
    else:
        g.user = User.query.get(user_id)

@bp.route('/logout/')
def logout():
    session.clear()
    return redirect(url_for('main.index'))

def login_required(view):
    @functools.wraps(view)
    def wrapped_view(**kwargs):
        if (g.user is None) or (g.user.power=="wait"):
            return redirect(url_for('user.login'))
        return view(**kwargs)
    return wrapped_view

@bp.route('/list/')
@login_required
def user_list():
    if g.user.power != "admin":
        return redirect(url_for('user.login'))
    user_list = User.query.order_by(User.power.asc(), User.truename.asc())
    return render_template('user/user_list.html', user_list=user_list)

@bp.route('/modify/<int:user_id>', methods=('GET', 'POST'))
@login_required
def user_modify(user_id):
    user = User.query.get_or_404(user_id)

    if request.method == 'POST':
        form = UserModifyForm()
        if form.validate_on_submit():
            form.populate_obj(user)
            db.session.commit()
            return redirect(url_for('user.user_list', user_id=user_id))
    else:
        form = UserModifyForm(obj=user)
    return render_template('user/modify.html', form=form)

@bp.route('/delete/<int:user_id>')
@login_required
def user_delete(user_id):
    user = User.query.get_or_404(user_id)

    db.session.delete(user)
    db.session.commit()
    return redirect(url_for('user.user_list'))

app/templates/menu/endline.html
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href="login.html">Logout</a>
                </div>
            </div>
        </div>
    </div>

app/templates/menu/footer.html
      <footer class="sticky-footer">
        <div class="container my-auto">
          <div class="copyright text-center my-auto">
            <span>Copyright &copy; 2020-2020 DAON Engineering Ltd is registered Korea.</span>
          </div>
        </div>
      </footer>

app/templates/menu/sidebar.html
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{{ url_for('main.index') }}">
        <div class="sidebar-brand-icon  pr-1 pl-1">
            <img src="{{ url_for('static', filename='img/doms_logo3.png') }}" width="40">
        </div>
        <div class="sidebar-brand-text mx-1">
            <img src="{{ url_for('static', filename='img/doms_logo4.png') }}" width="110">
        </div>
        <!--
        <div class="sidebar-brand-icon rotate-n-15"><i class="fab fa-studiovinari"></i></div>
        <div class="sidebar-brand-text mx-1"><h4>DOMS<sup><small> tf</small></sup></h4></div>
        -->
    </a>

    <!-- 구분선 --><hr class="sidebar-divider my-0">

    <!-- Nav Item - Dashboard -->
    <li class="nav-item active">
        <a class="nav-link" href="{{ url_for('main.index') }}">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Summary</span>
        </a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Heading -->
    <div class="sidebar-heading"> Measuaring </div>

    <!-- Nav Item - Pages Collapse Menu -->
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
            <i class="fas fa-fw fa-globe-asia"></i>
            <span>Site</span>
        </a>
        <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">Site Infomation:</h6>
                <a class="collapse-item" href="{{ url_for('site.site_detail') }}">현장 정보</a>
                <a class="collapse-item" href="{{ url_for('site.site_map') }}">현장 도면</a>
                <a class="collapse-item" href="{{ url_for('site.site_volume') }}">계측 수량</a>
                <a class="collapse-item" href="{{ url_for('site.site_frequency') }}">계측 빈도</a>
                <a class="collapse-item" href="{{ url_for('site.site_standard') }}">관리기준치</a>
                <a class="collapse-item" href="{{ url_for('site.site_progress') }}">현장 진척도</a>
            </div>
        </div>
    </li>

    <!-- Nav Item - Utilities Collapse Menu -->
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities" aria-expanded="true" aria-controls="collapseUtilities">
            <i class="fas fa-fw fa-chart-area"></i>
            <span>Point</span>
        </a>
        <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">Measuring Point:</h6>
                <a class="collapse-item" href="{{ url_for('point.point_list') }}">전체</a>
                <a class="collapse-item" href="{{ url_for('point.point_list_area', area_choice=0) }}">구역별</a>
                <a class="collapse-item" href="{{ url_for('point.point_list_point', point_choice=0) }}">종류별</a>
                <a class="collapse-item" href="{{ url_for('point.point_real') }}">실시간 계측</a>
            </div>
        </div>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Heading -->
    <div class="sidebar-heading">
        Staff Menu
    </div>

    <!-- Nav Item - Pages Collapse Menu -->
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages" aria-expanded="true" aria-controls="collapsePages">
            <i class="fas fa-fw fa-folder"></i>
            <span>Paper</span>
        </a>
        <div id="collapsePages" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">Active:</h6>
                <a class="collapse-item" href="{{ url_for('paper.paper_week') }}">주간보고서</a>
                <a class="collapse-item" href="{{ url_for('paper.paper_week') }}">월간보고서</a>
                <div class="collapse-divider"></div>
                <h6 class="collapse-header">finished:</h6>
                <a class="collapse-item" href="{{ url_for('paper.paper_week') }}">종료보고서</a>
            </div>
        </div>
    </li>

    <!-- Nav Item -->
    <li class="nav-item">
        <a class="nav-link" href="{{ url_for('analysis.anal_dateset') }}">
            <i class="fas fa-chart-pie"></i>
            <span>Analysis</span></a>
    </li>

    <!-- Nav Item - Tables -->
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#adminPages" aria-expanded="true" aria-controls="collapsePages">
            <i class="fas fa-fw fa-wrench"></i>
            <span>Admin</span>
        </a>
        <div id="adminPages" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">manage:</h6>
                <a class="collapse-item" href="{{ url_for('user.user_list') }}">사용자 관리</a>
                <a class="collapse-item" href="register.html">계측항목 관리</a>
                <div class="collapse-divider"></div>
                <h6 class="collapse-header">Backup:</h6>
                <a class="collapse-item" href="{{ url_for('static',filename='111.xlsx') }}" download>Database 백업</a>
            </div>
        </div>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider d-none d-md-block">

    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>
</ul>

app/templates/menu/topbar.html
        <!-- Topbar -->
        <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
            <!-- Sidebar Toggle (Topbar) -->
            <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                <i class="fa fa-bars"></i>
            </button>

            <!-- Topbar Search -->
            <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
                <div class="input-group">
                    <input type="text" class="form-control bg-light border-0 small"
                           placeholder="Search for..." aria-label="Search2" aria-describedby="basic-addon2" >
                    <div class="input-group-append">
                        <button class="btn btn-primary" type="button">
                            <i class="fas fa-search fa-sm"></i>
                        </button>
                    </div>
                </div>
            </form>

            <!-- Topbar Navbar -->
            <ul class="navbar-nav ml-auto">
                <div class="topbar-divider d-none d-sm-block"></div>

                <!-- Nav Item - User Information -->
                <li class="nav-item dropdown no-arrow">
                    {% if g.user %}
                        <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{ g.user.truename }}[{{ g.user.power }}]님 환영합니다.</span>
                            <h3 class="mt-2 text-primary"><i class="fas fa-user-circle"></i></h3>
                        </a>
                        <!-- Dropdown - User Information -->
                        <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                            <a class="dropdown-item text-gray-600" href="#">
                                <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>회원정보
                            </a>
                            <a class="dropdown-item text-gray-600" href="#">
                                <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>설정
                            </a>
                            <a class="dropdown-item text-gray-600" href="#">
                                <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>활동기록
                            </a>
                            <div class="dropdown-divider text-gray-600"></div>
                            <a class="dropdown-item text-gray-600" href="{{ url_for('user.logout') }}">
                                <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>나가기
                            </a>
                        </div>
                    {% else %}
                        <a class="nav-link dropdown-toggle" href="{{ url_for('user.login') }}" role="button">
                            <span class="mr-2 d-none d-lg-inline text-gray-600 small">로그인이 필요합니다.</span>
                            <h5 class="mt-2 "><i class="fas fa-user-alt-slash"></i></h5>
                        </a>
                    {% endif %}
                </li>
            </ul>
        </nav>