app/views/data_views.py
from flask import Blueprint, url_for, request, render_template, g, flash
from werkzeug.utils import redirect

from app import db
from app.models import Site, Point, Data
from app.forms import DataForm, DataVerticalForm, DataLoadcellForm
from app.views.user_views import login_required

bp = Blueprint('data', __name__, url_prefix='/data')


@bp.route('/create/<int:point_id>', methods=('GET', 'POST'))
@login_required
def data_create(point_id):
    point = Point.query.get_or_404(point_id)

    if point.type == "지중경사계":
        form = DataVerticalForm()
    elif point.type == "하중계":
        form = DataLoadcellForm()
    else:
        form = DataForm()

    if request.method == 'POST' and form.validate_on_submit():
        if point.type == '지중경사계':
            data = Data(measuringdate=form.measuringdate.data, data09=form.data09.data)
        elif point.type == "하중계":
            data = Data(measuringdate=form.measuringdate.data, data01=form.data01.data,
                        data02=form.data02.data, data03=form.data03.data)
        else:
            data = Data(measuringdate=form.measuringdate.data, data01=form.data01.data)
        point.data_set.append(data)
        db.session.add(data)
        db.session.commit()
        return redirect(url_for('point.point_detail', point_id=point_id))

    if point.type == '지중경사계':
        return render_template('data/vertical_form.html', form=form)
    else:
        return render_template('data/data_form.html', form=form)

@bp.route('/modify/<int:data_id>', methods=('GET', 'POST'))
@login_required
def data_modify(data_id):
    data = Data.query.get_or_404(data_id)

    if request.method == 'POST':
        if data.point.type == '지중경사계':
            form = DataVerticalForm()
        elif data.point.type == "하중계":
            form = DataLoadcellForm()
        else:
            form = DataForm()

        if form.validate_on_submit():
            form.populate_obj(data)
            db.session.commit()
            return redirect(url_for('point.point_detail', point_id=data.point_id))
    else:
        if data.point.type == '지중경사계':
            form = DataVerticalForm(obj=data)
        elif data.point.type == "하중계":
            form = DataLoadcellForm(obj=data)
        else:
            form = DataForm(obj=data)

    if data.point.type == '지중경사계':
        return render_template('data/vertical_form.html', form=form)
    else:
        return render_template('data/data_form.html', form=form)

@bp.route('/delete/<int:data_id>')
@login_required
def data_delete(data_id):
    data = Data.query.get_or_404(data_id)
    point_id = data.point.id

    db.session.delete(data)
    db.session.commit()
    return redirect(url_for('point.point_detail', point_id=point_id))

app/views/paper_views.py
from flask import Blueprint, render_template, request, url_for, g, flash
from werkzeug.utils import redirect
from datetime import datetime
import openpyxl

from app import db
from app.models import Site, Point, Data
from app.forms import PointForm
from app.views.user_views import login_required

bp = Blueprint('paper', __name__, url_prefix='/paper')

@bp.route('/week/')
@login_required
def paper_week():
    point_list = Point.query.all()
    return render_template('paper/paper_week.html', point_list=point_list)

@bp.route('/print_data/<int:point_id>, how_page, from_dateg, to_dateg')
@login_required
def data_print(point_id):
    site = Site.query.get_or_404(1)
    point = Point.query.get_or_404(point_id)
    page_type = request.args.get('how_page')
    from_date = request.args.get('from_dateg')
    to_date = request.args.get('to_dateg')

    if from_date == "초기데이터" and to_date == "최종데이터":
        data_list = Data.query.filter_by(point_id=point_id).order_by(Data.measuringdate)
        data_list_ea = Data.query.filter_by(point_id=point_id).order_by(Data.measuringdate).count()
    elif from_date == "초기데이터":
        data_list = Data.query.filter_by(point_id=point_id).\
            filter(Data.measuringdate <= to_date).order_by(Data.measuringdate)
        data_list_ea = Data.query.filter_by(point_id=point_id).\
            filter(Data.measuringdate <= to_date).order_by(Data.measuringdate).count()
    elif to_date == "최종데이터":
        data_list = Data.query.filter_by(point_id=point_id).\
            filter(Data.measuringdate >= from_date).order_by(Data.measuringdate)
        data_list_ea = Data.query.filter_by(point_id=point_id).\
            filter(Data.measuringdate >= from_date).order_by(Data.measuringdate).count()
    else:
        data_list = Data.query.filter_by(point_id=point_id).\
            filter(Data.measuringdate >= from_date).\
            filter(Data.measuringdate <= to_date).\
            order_by(Data.measuringdate)
        data_list_ea = Data.query.filter_by(point_id=point_id).\
            filter(Data.measuringdate >= from_date).\
            filter(Data.measuringdate <= to_date).\
            order_by(Data.measuringdate).count()

    if data_list_ea != 0 :
        if point.type == "지중경사계":
            min_value = max_value = 0.0
            if data_list[-1]:
                for inclino in data_list[-1].data09.split(','):
                    if max_value < float(inclino): max_value = float(inclino)
                    if min_value > float(inclino): min_value = float(inclino)
                if abs(max_value) > abs(min_value):
                    point.cst16 = max_value
                else:
                    point.cst16 = min_value
                db.session.commit()
            return render_template('paper/data_print.html', point=point, site=site, data_list=data_list, \
                                   data_list_ea=data_list_ea, from_date=from_date, to_date=to_date)
        else:
            old_date = data_list[0].measuringdate
            old_termDisplacement = 0
            for data in data_list:
                data.data11 = (datetime.strptime(str(data.measuringdate), "%Y-%m-%d %H:%M:%S") - datetime.strptime(str(point.startdate), "%Y-%m-%d")).days
                data.data12 = (datetime.strptime(str(data.measuringdate), "%Y-%m-%d %H:%M:%S") - datetime.strptime(str(old_date), "%Y-%m-%d %H:%M:%S")).days

                if point.type == "지하수위계":
                    data.data13 = (data.data01 - data_list[0].data01)
                    if data.data12 != 0:
                        data.data14 = (data.data13 - old_termDisplacement) / data.data12
                    else:
                        data.data14 = 0

                if point.type == "하중계":
                    data.data04 = point.cst12*(point.cst13-(data.data01+data.data02+data.data03))

                if point.type == "지표침하계":
                    data.data13 = (data.data01 - data_list[0].data01) * 1000
                elif point.type == "하중계":
                    if Data.query.filter_by(point_id=point_id).count()  > 1:
                        data.data13 = float(data.data04 - data_list[0].data04)
                    else:
                        data.data13 = 0
                else:
                    data.data13 = (data.data01 - data_list[0].data01)

                if point.type == "변형률계":
                    data.data04 = data.data13/1000000 * point.cst11
                    data.data15 = data.data04 - old_termDisplacement
                    old_termDisplacement = data.data04
                else:
                    data.data15 = data.data13 - old_termDisplacement
                    old_termDisplacement = data.data13
                old_date = data.measuringdate
            db.session.commit()
            if point.type == "지하수위계": point.cst16 = data.data14
            else: point.cst16 = data.data13
            db.session.commit()
            return render_template('paper/data_print.html', point=point, site=site, data_list=data_list, \
                                   data_list_ea=data_list_ea, from_date=from_date, to_date=to_date, page_type=page_type)
    else:
        return render_template('paper/data_print.html', point=point, site=site, data_list=data_list,\
                               flowdate=0, data_list_ea=data_list_ea, \
                               from_date=from_date, to_date=to_date, page_type=page_type)

app/views/point_views.py
from flask import Blueprint, render_template, request, url_for, g, flash
from werkzeug.utils import redirect
from datetime import datetime, timedelta
import babel

from app import db
from app.models import Site, Point, Data
from app.forms import PointForm
from app.views.user_views import login_required

bp = Blueprint('point', __name__, url_prefix='/point')

from_date = '초기데이터'
to_date = '최종데이터'

@bp.route('/list/')
@login_required
def point_list():
    point_list = Point.query.order_by(Point.area.asc(), Point.number.asc()) # desc()
    return render_template('point/point_list.html', point_list=point_list)

@bp.route('/list_area/<area_choice>/')
@login_required
def point_list_area(area_choice):
    from app.defines import area_types
    area_types = area_types()

    if area_choice != "0":
        point_list = Point.query.filter(Point.area == area_choice).order_by(Point.number.asc()) # desc()
    else:
        point_list = Point.query.filter(Point.area == area_types[0][0]).order_by(Point.number.asc())  # desc()
    return render_template('point/point_list_area.html', point_list=point_list, area_types=area_types)

@bp.route('/list_point/<point_choice>/')
@login_required
def point_list_point(point_choice):
    from app.defines import point_types
    point_types = point_types()
    point_kind = []
    for point_type in point_types:
        for point in point_type:
            if point_kind.count(point[0]):
                pass
            else:
                point_kind.append(point[0])

    if point_choice != "0":
        point_list = Point.query.filter(Point.type == point_choice).order_by(Point.area.asc()) # desc()
    else:
        point_list = Point.query.filter(Point.type == point_types[0][0][0]).order_by(Point.area.asc())  # desc()
    return render_template('point/point_list_point.html', point_list=point_list, point_kind=point_kind)

@bp.route('/real/')
@login_required
def point_real():
    return render_template('point/point_real.html')

@bp.route('/create/', methods=('GET', 'POST'))
@login_required
def point_create():
    form = PointForm()
    if request.method == 'POST' and form.validate_on_submit():
        point = Point(area=form.area.data, number=form.number.data, type=form.type.data,
                      installdate=form.installdate.data, startdate=form.startdate.data,
                      enddate=form.enddate.data, locate=form.locate.data, active=form.active.data,
                      cst01=form.cst01.data, cst02=form.cst02.data, cst03=form.cst03.data,
                      cst04=form.cst04.data, cst05=form.cst05.data, cst06=form.cst06.data,
                      cst07=form.cst07.data, cst08=form.cst08.data, cst09=form.cst09.data,
                      cst10=form.cst10.data, cst11=form.cst11.data, cst12=form.cst12.data,
                      cst13=form.cst13.data, cst14=form.cst14.data, cst15=form.cst15.data )
        db.session.add(point)
        db.session.commit()
        return redirect(url_for('point.point_list'))
    return render_template('point/point_form.html', form=form)

@bp.route('/detail/<int:point_id>/')
@login_required
def point_detail(point_id):
    site = Site.query.get_or_404(1)
    point = Point.query.get_or_404(point_id)

    if from_date == "초기데이터" and to_date == "최종데이터":
        data_list = Data.query.filter_by(point_id=point_id).order_by(Data.measuringdate)
        data_list_ea = Data.query.filter_by(point_id=point_id).order_by(Data.measuringdate).count()
        data_list_org = Data.query.filter_by(point_id=point_id).order_by(Data.measuringdate)
    elif from_date == "초기데이터":
        data_list = Data.query.filter_by(point_id=point_id).\
            filter(Data.measuringdate <= to_date).order_by(Data.measuringdate)
        data_list_ea = Data.query.filter_by(point_id=point_id).\
            filter(Data.measuringdate <= to_date).order_by(Data.measuringdate).count()
        data_list_org = Data.query.filter_by(point_id=point_id).order_by(Data.measuringdate)
    elif to_date == "최종데이터":
        data_list = Data.query.filter_by(point_id=point_id).\
            filter(Data.measuringdate >= from_date).order_by(Data.measuringdate)
        data_list_ea = Data.query.filter_by(point_id=point_id).\
            filter(Data.measuringdate >= from_date).order_by(Data.measuringdate).count()
        data_list_org = Data.query.filter_by(point_id=point_id).order_by(Data.measuringdate)
    else:
        data_list = Data.query.filter_by(point_id=point_id).\
            filter(Data.measuringdate >= from_date).\
            filter(Data.measuringdate <= to_date).\
            order_by(Data.measuringdate)
        data_list_ea = Data.query.filter_by(point_id=point_id).\
            filter(Data.measuringdate >= from_date).\
            filter(Data.measuringdate <= to_date).\
            order_by(Data.measuringdate).count()
        data_list_org = Data.query.filter_by(point_id=point_id).order_by(Data.measuringdate)

    if data_list_ea != 0 :
        if point.type == "지중경사계":
            min_value = max_value = 0.0
            if data_list_org[-1]:
                for inclino in data_list_org[-1].data09.split(','):
                    if max_value < float(inclino): max_value = float(inclino)
                    if min_value > float(inclino): min_value = float(inclino)
                if abs(max_value) > abs(min_value):
                    point.cst16 = max_value
                else:
                    point.cst16 = min_value
                point.cst18 = abs(point.cst16 / point.cst01 * 100)
                db.session.commit()
            return render_template('point/point_detail.html', point=point, site=site, data_list=data_list, \
                                   data_list_ea=data_list_ea, from_date=from_date, to_date=to_date)
        else:
            old_date = data_list_org[0].measuringdate
            old_termDisplacement = 0
            for data in data_list_org:
                data.data11 = (datetime.strptime(str(data.measuringdate), "%Y-%m-%d %H:%M:%S") - datetime.strptime(str(point.startdate), "%Y-%m-%d")).days
                data.data12 = (datetime.strptime(str(data.measuringdate), "%Y-%m-%d %H:%M:%S") - datetime.strptime(str(old_date), "%Y-%m-%d %H:%M:%S")).days

                if point.type == "지하수위계":
                    data.data13 = (data.data01 - data_list[0].data01)
                    if data.data12 != 0:
                        data.data14 = (data.data13 - old_termDisplacement) / data.data12
                    else:
                        data.data14 = 0

                if point.type == "하중계":
                    data.data04 = point.cst12*(point.cst13-(data.data01+data.data02+data.data03))

                if point.type == "지표침하계":
                    data.data13 = (data.data01 - data_list[0].data01) * 1000
                elif point.type == "하중계":
                    if Data.query.filter_by(point_id=point_id).count()  > 1:
                        data.data13 = float(data.data04 - data_list_org[0].data04)
                    else:
                        data.data13 = 0
                else:
                    data.data13 = (data.data01 - data_list[0].data01)

                if point.type == "변형률계":
                    data.data04 = data.data13/1000000 * point.cst11
                    data.data15 = data.data04 - old_termDisplacement
                    old_termDisplacement = data.data04
                else:
                    data.data15 = data.data13 - old_termDisplacement
                    old_termDisplacement = data.data13
                old_date = data.measuringdate
            db.session.commit()
            if point.type == "지하수위계":
                point.cst16 = data.data14
            else:
                point.cst16 = data.data13

            point.cst18 = abs(point.cst16 / point.cst01 * 100)
            db.session.commit()
            return render_template('point/point_detail.html', point=point, site=site, \
                                   data_list=data_list, data_list_ea=data_list_ea, \
                                   from_date=from_date, to_date=to_date)
    else:
        return render_template('point/point_detail.html', point=point, site=site, data_list=data_list, \
                               flowdate=0, data_list_ea=data_list_ea, from_date=from_date, to_date=to_date)

@bp.route('/modify/<int:point_id>', methods=('GET', 'POST'))
@login_required
def point_modify(point_id):
    point = Point.query.get_or_404(point_id)

    if request.method == 'POST':
        form = PointForm()
        if form.validate_on_submit():
            form.populate_obj(point)
            db.session.commit()
            return redirect(url_for('point.point_detail', point_id=point_id))
    else:
        form = PointForm(obj=point)
    return render_template('point/point_form.html', form=form)

@bp.route('/delete/<int:point_id>')
@login_required
def point_delete(point_id):
    point = Point.query.get_or_404(point_id)

    db.session.delete(point)
    db.session.commit()
    return redirect(url_for('point.point_list'))

@bp.route('/dateinit/<int:point_id>')
@login_required
def date_init(point_id):
    global from_date, to_date
    from_date = '초기데이터'
    to_date = '최종데이터'
    return redirect(url_for('point.point_detail', point_id=point_id))

@bp.route('/datemodify/<int:point_id>', methods=('POST',))
@login_required
def date_modify(point_id):
    global from_date, to_date
    from_date = request.form['from_date']
    to_date = request.form['to_date']+'a'
    return redirect(url_for('point.point_detail', point_id=point_id))

app/templates/point/type/detail_vertical.html
<!-- 제목 & 버튼 -->
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">계측 데이터</h1>
    <div>
        {% if g.user.power != "user" %}
            <a href="{{ url_for('data.data_create', point_id=point.id) }}" class="btn btn-primary btn-icon-split">
                <span class="icon text-white-50"><i class="fas fa-flag"></i></span>
                <span class="text">데이터 입력하기</span>
            </a>
            <a href="{{ url_for('point.point_modify', point_id=point.id) }}" class="btn btn-info btn-icon-split">
                <span class="icon text-white-50"><i class="fas fa-info-circle"></i></span>
                <span class="text">계측기 수정하기</span>
            </a>
        {% endif %}
            <a href="{{ url_for('paper.data_print', point_id=point.id, from_dateg=from_date, to_dateg=to_date) }}" class="btn btn-success btn-icon-split" target="_blank.">
                <span class="icon text-white-50"><i class="fas fa-print"></i></i></span>
                <span class="text">프린터 출력</span>
            </a>
        {% if g.user.power != "user" %}
            <a href="#" class="btn btn-danger btn-icon-split delete" data-uri="{{ url_for('point.point_delete', point_id=point.id) }}">
                <span class="icon text-white-50"><i class="fas fa-trash"></i></span>
                <span class="text">계측기 삭제하기</span>
            </a>
        {% endif %}
    </div>
</div>

<!-- 내용 시작 -->
<div class="card shadow mb-4">
    <!-- 내용 타이틀 -->
    <div class="card-header py-3">
        <div class="row">
            <div class="col-xl-6 col-md-12">
                <h6 class="m-0 font-weight-bold text-primary">
                    <a class="collapse-item" href="{{ url_for('point.point_list') }}">
                        <small>{{ site.nickname }}</small></a>  >
                    <a class="collapse-item" href="{{ url_for('point.point_list_area', area_choice=point.area) }}">
                        <small>{{ point.area }}</small></a> >
                    <a class="collapse-item" href="{{ url_for('point.point_list_point', point_choice=point.type) }}">
                        <small>{{ point.type }}</small></a> >
                    {{ point.number }}
                </h6>
            </div>
            <div class="col-xl-6 col-md-12 text-right">
                {% if from_date == '초기데이터' and to_date == '최종데이터' %}
                    <small>기한 : 전체&nbsp;</small>
                {% elif from_date == '초기데이터' %}
                    <small>기한 : 초기일 ~ {{to_date[1:10]}}&nbsp;</small>
                {% elif to_date == '최종데이터' %}
                    <small>기한 : {{from_date}} ~ 최종측정일&nbsp;</small>
                {% else %}
                    <small>기한 : {{from_date}} ~ {{to_date[0:10]}}&nbsp;</small>
                {% endif %}

                <a data-toggle="modal" href="#myModal" class="small text-info">
                    <i class="fas fa-info-circle"></i>
                </a> |
                <!-- Modal -->
                <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content text-center">
                            <div class="modal-header text-center">
                                <h5 class="modal-title">계측기간 설정</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body text-left">
                                <form action="{{ url_for('point.date_modify', point_id=point.id) }}" method="post">
                                    <div class="form-group">
                                        <label for="from_date" class="control-label">시작일시: (0000-00-00)</label>
                                        <input type="text" class="form-control" id="from_date" name="from_date" value="{{from_date}}">
                                    </div>
                                    <div class="form-group">
                                        <label for="to_date" class="control-label">종료일시: (0000-00-00)</label>
                                        <input type="text" class="form-control" id="to_date" name="to_date" value="{{to_date[0:10]}}">
                                    </div>
                                    <button type="submit" class="btn btn-primary text-right">계측기간 설정하기</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>

                <a href="{{ url_for('point.date_init', point_id=point.id) }}" class="small text-danger">
                    <i class="fas fa-trash"></i>
                </a>
            </div>
        </div>
    </div>

    <div class="card-body ">
        <!-- Data Table 헤더-->
        <div class="table table-sm">
            <table class="table table-bordered" border="1" style="width: 100%;" >
                <tbody>
                    <tr style="height: 10px;">
                        <td style="width: 84.8064%; height: 21px; text-align: center;" colspan="4">
                            <h4>
                                <strong>{{ point.type }} DATA SHEET</strong>
                            </h4>
                        </td>
                        <td style="width: 15%; height: 105px;" rowspan="5"></td>
                    </tr>
                    <tr style="height: 21px;">
                        <td style="width: 15%; height: 21px; text-align: center;">현장명</td>
                        <td style="width: 69.8064%; height: 21px;" colspan="3">&nbsp;{{ site.fullname }}</td>
                    </tr>
                    <tr style="height: 21px;">
                        <td style="width: 15%; height: 21px; text-align: center;">계측기명</td>
                        <td style="width: 27.5171%; height: 21px;">&nbsp;{{ point.number }}</td>
                        <td style="width: 15%; height: 21px; text-align: center;">위치</td>
                        <td style="width: 27.2893%; height: 21px;">&nbsp;{{ point.area }} > {{ point.locate }}</td>
                    </tr>
                        <tr style="height: 21px;">
                        <td style="width: 15%; height: 21px; text-align: center;">설치일자</td>
                        <td style="width: 27.5171%; height: 21px;">&nbsp;{{ point.installdate }}</td>
                        <td style="width: 15%; height: 21px; text-align: center;">초기일자</td>
                        <td style="width: 27.2893%; height: 21px;">&nbsp;{{ point.startdate }}</td>
                    </tr>
                        <tr style="height: 21px;">
                        <td style="width: 15%; height: 21px; text-align: center;">설치심도</td>
                        <td style="width: 27.5171%; height: 21px;">&nbsp;{{ point.cst10/2 }} m</td>
                        <td style="width: 15%; height: 21px; text-align: center;">1차 관리기준치</td>
                        <td style="width: 27.2893%; height: 21px;">&nbsp;{{ point.cst01 }} mm</td>
                    </tr>
                </tbody>
            </table>
        </div>

        <div class="row">
            <!-- Data Table 내용-->
            <div class="col-xl-8 col-md-12">
                <div class="h-100 py-2">
                    {% if data_list_ea > 0 %}
                        <div>
                            <table class="table table-hover table-striped table-bordered table-condensed" cellspacing="0" id="table_point" >
                            <thead>
                                <tr class="thead-dark text-center">
                                    <th><small>Depth</small></th>
                                        {% for data in data_list %}
                                    <th><small>{{ data.measuringdate|datetime }}</small></th>
                                        {% endfor %}
                                </tr>
                            </thead>
                            <tbody >
                                {% if data_list %}
                                    {% for depth in range(point.cst10|int) %}
                                        <tr class="text-center" height="10">
                                            <th class="text-right"><small><b>{{ (depth+1)/2*-1 }}</b></small></th>
                                            {% for data in data_list %}
                                                {% if data.data09 != NULL %}
                                                    <td class="text-right">
                                                        <small>{{ '%0.2f'|format(data.data09.split(',')[point.cst10|int-1-depth]|float) }}</small>
                                                    </td>
                                                {% endif %}
                                            {% endfor %}
                                        </tr>
                                    {% endfor %}
                                    <tr class="text-center">
                                        <th><small><b>비고</b></small></th>
                                        {% for data in data_list %}
                                            <td class="text-right">
                                                {% if g.user.power != "user" %}
                                                    <a href="{{ url_for('data.data_modify', data_id=data.id) }}"
                                                        class="small text-info"><i class="fas fa-info-circle"></i>
                                                    </a> |
                                                    <a href="#" class="small delete text-danger"
                                                        data-uri="{{ url_for('data.data_delete', data_id=data.id) }}">
                                                        <i class="fas fa-trash"></i>
                                                    </a>
                                                {% endif %}
                                            </td>
                                        {% endfor %}
                                    </tr>
                                {% else %}
                                    <tr>
                                        <td colspan="3">No Data...</td>
                                    </tr>
                                {% endif %}
                            </tbody>
                            </table>
                        </div>
                    {% endif %}
                </div>
            </div>

            <!-- 그래프 블록 -->
            <div class="col-xl-4 col-md-12 mb-3 mt-2" style="height: 800px;">
                <div class="h-100 py-2">
                    <div class="chart-area table-bordered " border="1" style="width:100%; height:100%" >
                        <canvas class="p-3" id="myChart" ></canvas>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>