app/views/user_views.py
from flask import Blueprint, url_for, render_template, flash, request, session, g
from werkzeug.security import generate_password_hash, check_password_hash
from werkzeug.utils import redirect

from app import db
from app.forms import UserLoginForm, UserCreateForm, UserModifyForm
from app.models import User
import functools

bp = Blueprint('user', __name__, url_prefix='/user')

@bp.route('/signup/', methods=('GET', 'POST'))
def signup():
    form = UserCreateForm()
    if request.method == 'POST' and form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if not user:
            user = User(username=form.username.data,
                        password=generate_password_hash(form.password1.data),
                        truename = form.truename.data,
                        company=form.company.data,
                        phone=form.phone.data,
                        email=form.email.data,
                        power='wait')
            db.session.add(user)
            db.session.commit()
            return redirect(url_for('main.index'))
        else:
            flash('이미 존재하는 사용자입니다.')
    return render_template('user/signup.html', form=form)

@bp.route('/login/', methods=('GET', 'POST'))
def login():
    form = UserLoginForm()
    if request.method == 'POST' and form.validate_on_submit():
        error = None
        user = User.query.filter_by(username=form.username.data).first()
        if not user:
            error = "존재하지 않는 사용자입니다."
        elif not check_password_hash(user.password, form.password.data):
            error = "비밀번호가 올바르지 않습니다."
        elif user.power == "wait":
            error = "관리자의 사용 승인까지 기다려 주세요."
        if error is None:
            session.clear()
            session['user_id'] = user.id
            return redirect(url_for('main.index'))
        flash(error)
    return render_template('user/login.html', form=form)

@bp.before_app_request
def load_logged_in_user():
    user_id = session.get('user_id')
    if user_id is None:
        g.user = None
    else:
        g.user = User.query.get(user_id)

@bp.route('/logout/')
def logout():
    session.clear()
    return redirect(url_for('main.index'))

def login_required(view):
    @functools.wraps(view)
    def wrapped_view(**kwargs):
        if (g.user is None) or (g.user.power=="wait"):
            return redirect(url_for('user.login'))
        return view(**kwargs)
    return wrapped_view

@bp.route('/list/')
@login_required
def user_list():
    if g.user.power != "admin":
        return redirect(url_for('user.login'))
    user_list = User.query.order_by(User.power.asc(), User.truename.asc())
    return render_template('user/user_list.html', user_list=user_list)

@bp.route('/modify/<int:user_id>', methods=('GET', 'POST'))
@login_required
def user_modify(user_id):
    user = User.query.get_or_404(user_id)

    if request.method == 'POST':
        form = UserModifyForm()
        if form.validate_on_submit():
            form.populate_obj(user)
            db.session.commit()
            return redirect(url_for('user.user_list', user_id=user_id))
    else:
        form = UserModifyForm(obj=user)
    return render_template('user/modify.html', form=form)

@bp.route('/delete/<int:user_id>')
@login_required
def user_delete(user_id):
    user = User.query.get_or_404(user_id)

    db.session.delete(user)
    db.session.commit()
    return redirect(url_for('user.user_list'))

app/templates/user/login.html
<!DOCTYPE html>
<html lang="ko">

<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>다온계측시스템 DOMS</title>

    <link rel="stylesheet" href="{{ url_for('static', filename='vendor/fontawesome-free/css/all.min.css') }}" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/sb-admin-2.min.css') }}">

    <style>
        #bg {
            background-image:url({{ url_for('static', filename='img/login_src.jpg') }});
            background-repeat:no-repeat;
            background-position:center;
        }
    </style>


</head>

<body class="bg-gradient-primary">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-xl-10 col-lg-12 col-md-9">
                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-0">
                        <div class="row">
                            <div class="col-lg-6 d-none d-lg-block " id="bg"></div> <!--width="460" height="400"-->
                            <div class="col-lg-6">
                            <div class="p-5">
                            <div class="text-center">
                                <h1 class="h4 text-gray-900 mb-4">DOMS에 오신 것을 환영합니다!</h1>
                            </div>
                            <form method="post" class="post-form my-3">
                                {{ form.csrf_token }} <!-- CSRF -->
                                {% include "form_errors.html" %}

                                <div class="form-group">
                                    {{ form.username(class="form-control form-control-user") }}
                                </div>
                                <div class="form-group">
                                    {{ form.password(class="form-control form-control-user") }}
                                </div>
                                <button type="submit" class="btn btn-primary btn-user btn-block">
                                    <span class="text">DOMS 입장하기</span>
                                </button>
                            </form>
                            <hr>
                            <div class="text-center">
                                <a class="small" href="{{ url_for('user.signup') }}">비밀번호를 분실하셨나요?</a>
                            </div>
                            <div class="text-center">
                                <a class="small" href="{{ url_for('user.signup') }}">유저 가입이 필요하신가요?</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="{{ url_for('static', filename='js/jquery-3.5.1.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
    <script src="{{ url_for('static', filename='vendor/jquery-easing/jquery.easing.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/sb-admin-2.min.js') }}"></script>

</body>

</html>

app/templates/user/modify.html
{% extends 'base.html' %}
{% block content %}

    <style>
        #bg {
            background-image:url({{ url_for('static', filename='img/signup_src.jpg') }});
            background-repeat:no-repeat;
            background-position:center;
        }
    </style>

    <div class="container">
        <div class="card o-hidden border-0 shadow-lg my-5">
            <div class="card-body p-0">
                <div class="row">
                    <div class="col-lg-5 d-none d-lg-block" id="bg"> </div> <!--width="450" height="600"-->
                <div class="col-lg-7">
                    <div class="p-5">
                        <div class="text-center">
                            <h1 class="h4 text-gray-900 mb-4">사용자 정보</h1>
                        </div>
                        <form method="post" class="post-form my-3">
                            {{ form.csrf_token }} <!-- CSRF -->
                            {% include "form_errors.html" %}

                            <div class="form-group ">
                                사용자명 : {{ form.truename(class="form-control form-control-user ") }}
                            </div>
                            <div class="form-group">
                                회사 : {{ form.company(class="form-control form-control-user") }}
                            </div>
                            <div class="form-group">
                                연락처 : {{ form.phone(class="form-control form-control-user") }}
                            </div>
                            <div class="form-group">
                                이메일 : {{ form.email(class="form-control form-control-user") }}
                            </div>
                            <div class="form-group">
                                권한 : {{ form.power(class="form-control form-control-user") }}
                            </div>
                            <button type="submit" class="btn btn-primary btn-user btn-block">
                                <span class="text">사용자 정보 수정</span>
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

app/templates/user/signup.html
<!DOCTYPE html>
<html lang="ko">

<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>다온계측시스템 DOMS</title>

    <link rel="stylesheet" href="{{ url_for('static', filename='vendor/fontawesome-free/css/all.min.css') }}" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/sb-admin-2.min.css') }}">

    <style>
        #bg {
            background-image:url({{ url_for('static', filename='img/signup_src.jpg') }});
            background-repeat:no-repeat;
            background-position:center;
        }
    </style>

</head>

<body class="bg-gradient-primary">

    <div class="container">
        <div class="card o-hidden border-0 shadow-lg my-5">
            <div class="card-body p-0">
                <div class="row">
                    <div class="col-lg-5 d-none d-lg-block" id="bg"> </div> <!--width="450" height="600"-->
                <div class="col-lg-7">
                    <div class="p-5">
                        <div class="text-center">
                            <h1 class="h4 text-gray-900 mb-4">DOMS 유저 등록</h1>
                        </div>
                        <form method="post" class="post-form my-3">
                            {{ form.csrf_token }} <!-- CSRF -->
                            {% include "form_errors.html" %}

                            <div class="form-group">
                                {{ form.username(class="form-control form-control-user") }}
                            </div>
                            <div class="form-group row">
                                <div class="col-sm-6 mb-3 mb-sm-0">
                                    {{ form.password1(class="form-control form-control-user") }}
                                </div>
                                <div class="col-sm-6">
                                    {{ form.password2(class="form-control form-control-user") }}
                                </div>
                            </div>
                            <div class="form-group">
                                {{ form.truename(class="form-control form-control-user") }}
                            </div>
                            <div class="form-group">
                                {{ form.company(class="form-control form-control-user") }}
                            </div>
                            <div class="form-group">
                                {{ form.phone(class="form-control form-control-user") }}
                            </div>
                            <div class="form-group">
                                {{ form.email(class="form-control form-control-user") }}
                            </div>
                            <button type="submit" class="btn btn-primary btn-user btn-block">
                                <span class="text">유저 등록</span>
                            </button>
                        </form>
                        <hr>
                        <div class="text-center">
                            <a class="small" href="{{ url_for('user.login') }}">이미 가입하셨나요? 로그인!</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="{{ url_for('static', filename='js/jquery-3.5.1.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
    <script src="{{ url_for('static', filename='vendor/jquery-easing/jquery.easing.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/sb-admin-2.min.js') }}"></script>

</body>

</html>

app/templates/user/user_list.html
{% extends 'base.html' %}
{% block content %}

    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">사용자 관리</h1>
    </div>

    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">
                User List
            </h6>
        </div>

        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-hover table-striped table-bordered table-condensed" id="table_point" width="100%" cellspacing="0">
                    <thead style="text-align: center;">
                        <tr class="thead-dark">
                            <th>No.</th>
                            <th>ID</th>
                            <th>이름</th>
                            <th>회사</th>
                            <th>연락처</th>
                            <th>E-Mail</th>
                            <th>power</th>
                            <th>비고</th>
                        </tr>
                    </thead>

                    <tbody style="text-align: center;">
                        {% if user_list %}
                            {% for user in user_list %}
                            <tr>
                                <td>{{ loop.index }}</td>
                                <td>{{ user.username }}</td>
                                <td>{{ user.truename }}</td>
                                <td>{{ user.company }}</td>
                                <td>{{ user.phone }}</td>
                                <td>{{ user.email }}</td>
                                <td>{{ user.power }}</td>
                                <td>
                                    <a href="{{ url_for('user.user_modify', user_id=user.id) }}"
                                       class="small text-info"><i class="fas fa-info-circle"></i>
                                    </a> |
                                    <a href="#" class="small delete text-danger"
                                       data-uri="{{ url_for('user.user_delete', user_id=user.id) }}">
                                        <i class="fas fa-trash"></i>
                                    </a>
                                </td>
                             </tr>
                            {% endfor %}
                        {% else %}
                            <tr>
                                <td colspan="3">계측기가 없습니다.</td>
                            </tr>
                        {% endif %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

{% endblock %}

{% block script %}
<script type="text/javascript">
// 계측기 삭제확인 js
$(document).ready(function(){
    $(".delete").on('click', function() {
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = $(this).data('uri');
        }
    });
});

jQuery(function($){
	$("#table_point").DataTable(
	    {
	        "paging"        : true,                 //페이징
	        "ordering"      : true,                 //컬럼 클릭 시 오더링을 적용
	        "info"          : true,                 //페이지 상태에대한 정보를 표시
	        "filter"        : true,                 //검색창
	        "lengthChange"  : true,                 //블록 단위 변경 기능
	        //"order"         : [[ 0, "desc" ]],      //기본 컬럼 정렬 설정
	        "scrollX"       : false,
	        "scrollY"       : false,
	        "scrollCollapse": false,
            "language": {
                "emptyTable": "사용자가 없어요.",
                "lengthMenu": "인원 _MENU_ 명씩 보기",
                "info": "사용자 수 : 현재 _START_ - _END_명 / 총_TOTAL_명",
                "infoEmpty": "유저 없음",
                "infoFiltered": "( _MAX_건의 데이터에서 필터링됨 )",
                "search": "검색: ",
                "zeroRecords": "일치하는 사용자가 없어요.",
                "loadingRecords": "로딩중...",
                "processing":     "잠시만 기다려 주세요...",
                "paginate": {
                    "next": "다음",
                    "previous": "이전"
                }
            },
	    }
	);
});
</script>
{% endblock %}