app/views/point_views.py
from flask import Blueprint, render_template, request, url_for, g, flash
from werkzeug.utils import redirect
from datetime import datetime, timedelta
import babel

from app import db
from app.models import Site, Point, Data
from app.forms import PointForm
from app.views.user_views import login_required

bp = Blueprint('point', __name__, url_prefix='/point')

from_date = '초기데이터'
to_date = '최종데이터'

@bp.route('/list/')
@login_required
def point_list():
    point_list = Point.query.order_by(Point.area.asc(), Point.number.asc()) # desc()
    return render_template('point/point_list.html', point_list=point_list)

@bp.route('/list_area/<area_choice>/')
@login_required
def point_list_area(area_choice):
    from app.defines import area_types
    area_types = area_types()

    if area_choice != "0":
        point_list = Point.query.filter(Point.area == area_choice).order_by(Point.number.asc()) # desc()
    else:
        point_list = Point.query.filter(Point.area == area_types[0][0]).order_by(Point.number.asc())  # desc()
    return render_template('point/point_list_area.html', point_list=point_list, area_types=area_types)

@bp.route('/list_point/<point_choice>/')
@login_required
def point_list_point(point_choice):
    from app.defines import point_types
    point_types = point_types()
    point_kind = []
    for point_type in point_types:
        for point in point_type:
            if point_kind.count(point[0]):
                pass
            else:
                point_kind.append(point[0])

    if point_choice != "0":
        point_list = Point.query.filter(Point.type == point_choice).order_by(Point.area.asc()) # desc()
    else:
        point_list = Point.query.filter(Point.type == point_types[0][0][0]).order_by(Point.area.asc())  # desc()
    return render_template('point/point_list_point.html', point_list=point_list, point_kind=point_kind)

@bp.route('/real/')
@login_required
def point_real():
    return render_template('point/point_real.html')

@bp.route('/create/', methods=('GET', 'POST'))
@login_required
def point_create():
    form = PointForm()
    if request.method == 'POST' and form.validate_on_submit():
        point = Point(area=form.area.data, number=form.number.data, type=form.type.data,
                      installdate=form.installdate.data, startdate=form.startdate.data,
                      enddate=form.enddate.data, locate=form.locate.data, active=form.active.data,
                      cst01=form.cst01.data, cst02=form.cst02.data, cst03=form.cst03.data,
                      cst04=form.cst04.data, cst05=form.cst05.data, cst06=form.cst06.data,
                      cst07=form.cst07.data, cst08=form.cst08.data, cst09=form.cst09.data,
                      cst10=form.cst10.data, cst11=form.cst11.data, cst12=form.cst12.data,
                      cst13=form.cst13.data, cst14=form.cst14.data, cst15=form.cst15.data )
        db.session.add(point)
        db.session.commit()
        return redirect(url_for('point.point_list'))
    return render_template('point/point_form.html', form=form)

@bp.route('/detail/<int:point_id>/')
@login_required
def point_detail(point_id):
    site = Site.query.get_or_404(1)
    point = Point.query.get_or_404(point_id)

    if from_date == "초기데이터" and to_date == "최종데이터":
        data_list = Data.query.filter_by(point_id=point_id).order_by(Data.measuringdate)
        data_list_ea = Data.query.filter_by(point_id=point_id).order_by(Data.measuringdate).count()
        data_list_org = Data.query.filter_by(point_id=point_id).order_by(Data.measuringdate)
    elif from_date == "초기데이터":
        data_list = Data.query.filter_by(point_id=point_id).\
            filter(Data.measuringdate <= to_date).order_by(Data.measuringdate)
        data_list_ea = Data.query.filter_by(point_id=point_id).\
            filter(Data.measuringdate <= to_date).order_by(Data.measuringdate).count()
        data_list_org = Data.query.filter_by(point_id=point_id).order_by(Data.measuringdate)
    elif to_date == "최종데이터":
        data_list = Data.query.filter_by(point_id=point_id).\
            filter(Data.measuringdate >= from_date).order_by(Data.measuringdate)
        data_list_ea = Data.query.filter_by(point_id=point_id).\
            filter(Data.measuringdate >= from_date).order_by(Data.measuringdate).count()
        data_list_org = Data.query.filter_by(point_id=point_id).order_by(Data.measuringdate)
    else:
        data_list = Data.query.filter_by(point_id=point_id).\
            filter(Data.measuringdate >= from_date).\
            filter(Data.measuringdate <= to_date).\
            order_by(Data.measuringdate)
        data_list_ea = Data.query.filter_by(point_id=point_id).\
            filter(Data.measuringdate >= from_date).\
            filter(Data.measuringdate <= to_date).\
            order_by(Data.measuringdate).count()
        data_list_org = Data.query.filter_by(point_id=point_id).order_by(Data.measuringdate)

    if data_list_ea != 0 :
        if point.type == "지중경사계":
            min_value = max_value = 0.0
            if data_list_org[-1]:
                for inclino in data_list_org[-1].data09.split(','):
                    if max_value < float(inclino): max_value = float(inclino)
                    if min_value > float(inclino): min_value = float(inclino)
                if abs(max_value) > abs(min_value):
                    point.cst16 = max_value
                else:
                    point.cst16 = min_value
                point.cst18 = abs(point.cst16 / point.cst01 * 100)
                db.session.commit()
            return render_template('point/point_detail.html', point=point, site=site, data_list=data_list, \
                                   data_list_ea=data_list_ea, from_date=from_date, to_date=to_date)
        else:
            old_date = data_list_org[0].measuringdate
            old_termDisplacement = 0
            for data in data_list_org:
                data.data11 = (datetime.strptime(str(data.measuringdate), "%Y-%m-%d %H:%M:%S") - datetime.strptime(str(point.startdate), "%Y-%m-%d")).days
                data.data12 = (datetime.strptime(str(data.measuringdate), "%Y-%m-%d %H:%M:%S") - datetime.strptime(str(old_date), "%Y-%m-%d %H:%M:%S")).days

                if point.type == "지하수위계":
                    data.data13 = (data.data01 - data_list[0].data01)
                    if data.data12 != 0:
                        data.data14 = (data.data13 - old_termDisplacement) / data.data12
                    else:
                        data.data14 = 0

                if point.type == "하중계":
                    data.data04 = point.cst12*(point.cst13-(data.data01+data.data02+data.data03))

                if point.type == "지표침하계":
                    data.data13 = (data.data01 - data_list[0].data01) * 1000
                elif point.type == "하중계":
                    if Data.query.filter_by(point_id=point_id).count()  > 1:
                        data.data13 = float(data.data04 - data_list_org[0].data04)
                    else:
                        data.data13 = 0
                else:
                    data.data13 = (data.data01 - data_list[0].data01)

                if point.type == "변형률계":
                    data.data04 = data.data13/1000000 * point.cst11
                    data.data15 = data.data04 - old_termDisplacement
                    old_termDisplacement = data.data04
                else:
                    data.data15 = data.data13 - old_termDisplacement
                    old_termDisplacement = data.data13
                old_date = data.measuringdate
            db.session.commit()
            if point.type == "지하수위계":
                point.cst16 = data.data14
            else:
                point.cst16 = data.data13

            point.cst18 = abs(point.cst16 / point.cst01 * 100)
            db.session.commit()
            return render_template('point/point_detail.html', point=point, site=site, \
                                   data_list=data_list, data_list_ea=data_list_ea, \
                                   from_date=from_date, to_date=to_date)
    else:
        return render_template('point/point_detail.html', point=point, site=site, data_list=data_list, \
                               flowdate=0, data_list_ea=data_list_ea, from_date=from_date, to_date=to_date)

@bp.route('/modify/<int:point_id>', methods=('GET', 'POST'))
@login_required
def point_modify(point_id):
    point = Point.query.get_or_404(point_id)

    if request.method == 'POST':
        form = PointForm()
        if form.validate_on_submit():
            form.populate_obj(point)
            db.session.commit()
            return redirect(url_for('point.point_detail', point_id=point_id))
    else:
        form = PointForm(obj=point)
    return render_template('point/point_form.html', form=form)

@bp.route('/delete/<int:point_id>')
@login_required
def point_delete(point_id):
    point = Point.query.get_or_404(point_id)

    db.session.delete(point)
    db.session.commit()
    return redirect(url_for('point.point_list'))

@bp.route('/dateinit/<int:point_id>')
@login_required
def date_init(point_id):
    global from_date, to_date
    from_date = '초기데이터'
    to_date = '최종데이터'
    return redirect(url_for('point.point_detail', point_id=point_id))

@bp.route('/datemodify/<int:point_id>', methods=('POST',))
@login_required
def date_modify(point_id):
    global from_date, to_date
    from_date = request.form['from_date']
    to_date = request.form['to_date']+'a'
    return redirect(url_for('point.point_detail', point_id=point_id))

app/templates/point/point_detail.html
{% extends 'base.html' %}
{% block content %}

    {% if point.type == "지중경사계" %}
        {% include "point/type/detail_vertical.html" %}
    {% else %}
        {% include "point/type/detail_normal.html" %}
    {% endif %}

{% endblock %}

<!-- 계측기 삭제확인 js -->
<!-- 그래프 js -->
{% block script %}
<script type='text/javascript'>
    // 계측기 삭제확인 js
    $(document).ready(function(){
        $(".delete").on('click', function() {
            if(confirm("정말로 삭제하시겠습니까?")) {
                location.href = $(this).data('uri');
            }
        });
    });

    // 그래프 js
    {% if point.type == "지중경사계" %}
        {% include "point/type/graph_vertical.js" %}
    {% else %}
        {% include "point/type/graph_normal.js" %}
    {% endif %}

    // 데이터 js
    jQuery(function($){
        $("#table_point").DataTable(
            {
                {% if data_list_ea > 0 %}
                dom: 'frtipB',
                buttons: [
                    {
                        extend: 'copy'
                        ,className: 'btn btn-secondary btn-sm mt-1 '
                        ,text: '클립보드에 복사'
                        ,title: '{{point.number}}'
                    },
                    {
                        extend: 'excel'
                        ,className: 'btn btn-secondary btn-sm mt-1'
                        ,text: '엑셀 저장하기'
                        ,filename: 'DOMS_{{point.number}}_{{data_list[-1].measuringdate|datetime}}'
                        ,title: '{{point.number}}'
                    },
                    {
                        extend: 'csv'
                        ,className: 'btn btn-secondary btn-sm mt-1'
                        ,text: 'csv 저장하기'
                        ,filename: 'DOMS_{{point.number}}_{{data_list[-1].measuringdate|datetime}}'
                        ,bom: true
                    },
                ],
                {% endif %}
                "paging"        : false,                //페이징
                "ordering"      : false,                //컬럼 클릭 시 오더링을 적용
                "info"          : false,                //페이지 상태에대한 정보를 표시
                "filter"        : false,                //검색창
                "lengthChange"  : false,                //블록 단위 변경 기능
                "order"         : [[ 0, "desc" ]],      //기본 컬럼 정렬 설정
                "fixedHeader"   : true ,                // 헤더 고정
                {% if point.type == "지중경사계" %}
                    "scrollX"       : true,
                    "scrollY"       :"735px",
                    //"fixedColumns"  : { leftColumns: 1 } ,  // 왼쪽 컬럼 고정
                {% else %}
                    "scrollX"       : false,
                    {% if point.data_set|length > 15 %}
                        "scrollY"       :"500px",
                    {% else %}
                        "scrollY"       :false,
                    {% endif %}
                {% endif %}
                "scrollCollapse": false,
                "language": {
                    "emptyTable": "데이터가 없어요.",
                    "infoEmpty": "데이터 없음",
                    "zeroRecords": "일치하는 데이터가 없어요.",
                    "loadingRecords": "로딩중...",
                    "processing":     "잠시만 기다려 주세요...",
                },
            }
        );
    });

</script>
{% endblock %}

app/templates/point/point_list.html
{% extends 'base.html' %}
{% block content %}

<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">계측기 현황</h1>
    {% if g.user.power != "user" %}
        <a href="{{ url_for('point.point_create') }}" class="btn btn-primary btn-icon-split">
            <span class="icon text-white-50"><i class="fas fa-flag"></i></span>
            <span class="text">계측기 등록하기</span>
        </a>
    {% endif %}
</div>

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">
            Measuring Point List
        </h6>
    </div>
    {% include "point/list/point_listmodule.html" %}
</div>

{% endblock %}

{% block script %}
<script type="text/javascript">
jQuery(function($){
	$("#table_point").DataTable(
	    {
	        "paging"        : true,                 //페이징
	        "ordering"      : true,                 //컬럼 클릭 시 오더링을 적용
	        "info"          : true,                 //페이지 상태에대한 정보를 표시
	        "filter"        : true,                 //검색창
	        "lengthChange"  : true,                 //블록 단위 변경 기능
	        //"order"         : [[ 0, "desc" ]],      //기본 컬럼 정렬 설정
	        "scrollX"       : false,
	        "scrollY"       : false,
	        "scrollCollapse": false,
            "language": {
                "emptyTable": "계측기가 없어요.",
                "lengthMenu": "계측기 _MENU_ 개씩 보기",
                "info": "계측기 수 : 현재 _START_ - _END_개 / 총_TOTAL_개",
                "infoEmpty": "계측기 없음",
                "infoFiltered": "( _MAX_건의 데이터에서 필터링됨 )",
                "search": "검색: ",
                "zeroRecords": "일치하는 데이터가 없어요.",
                "loadingRecords": "로딩중...",
                "processing":     "잠시만 기다려 주세요...",
                "paginate": {
                    "next": "다음",
                    "previous": "이전"
                }
            },
	    }
	);
});
</script>
{% endblock %}

app/templates/point/point_list_area.html
{% extends 'base.html' %}
{% block content %}

<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">계측기 현황</h1>
    {% if g.user.power != "user" %}
        <a href="{{ url_for('point.point_create') }}" class="btn btn-primary btn-icon-split">
            <span class="icon text-white-50"><i class="fas fa-flag"></i></span>
            <span class="text">계측기 등록하기</span>
        </a>
    {% endif %}
</div>

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">
            Measuring Point List :
            {% for area_type in area_types %}
                <a href="{{ url_for('point.point_list_area', area_choice=area_type[0]) }}" class="btn btn-sm btn-primary btn-icon-split ml-2">
                    <span class="text">{{area_type[0]}}</span>
                </a>
            {% endfor %}
        </h6>
    </div>
    {% include "point/list/point_listmodule.html" %}
</div>

{% endblock %}

{% block script %}
<script type="text/javascript">
jQuery(function($){
	$("#table_point").DataTable(
	    {
	        "paging"        : true,                 //페이징
	        "ordering"      : true,                 //컬럼 클릭 시 오더링을 적용
	        "info"          : true,                 //페이지 상태에대한 정보를 표시
	        "filter"        : true,                 //검색창
	        "lengthChange"  : true,                 //블록 단위 변경 기능
	        //"order"         : [[ 0, "desc" ]],      //기본 컬럼 정렬 설정
	        "scrollX"       : false,
	        "scrollY"       : false,
	        "scrollCollapse": false,
            "language": {
                "emptyTable": "데이터가 없어요.",
                "lengthMenu": "계측기 _MENU_ 개씩 보기",
                "info": "계측기 수 : 현재 _START_ - _END_개 / 총_TOTAL_개",
                "infoEmpty": "데이터 없음",
                "infoFiltered": "( _MAX_건의 데이터에서 필터링됨 )",
                "search": "검색: ",
                "zeroRecords": "일치하는 데이터가 없어요.",
                "loadingRecords": "로딩중...",
                "processing":     "잠시만 기다려 주세요...",
                "paginate": {
                    "next": "다음",
                    "previous": "이전"
                }
            },
	    }
	);
});
</script>
{% endblock %}

app/templates/point/point_list_point.html
{% extends 'base.html' %}
{% block content %}

<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">계측기 현황</h1>
    {% if g.user.power != "user" %}
        <a href="{{ url_for('point.point_create') }}" class="btn btn-primary btn-icon-split">
            <span class="icon text-white-50"><i class="fas fa-flag"></i></span>
            <span class="text">계측기 등록하기</span>
        </a>
    {% endif %}
</div>

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">
            Measuring Point List :
            {% for point_kind in point_kind %}
                <a href="{{ url_for('point.point_list_point', point_choice=point_kind) }}"
                   class="btn btn-sm btn-primary btn-icon-split ml-2">
                    <span class="text">{{point_kind}}</span>
                </a>
            {% endfor %}
        </h6>
    </div>
    {% include "point/list/point_listmodule.html" %}
</div>

{% endblock %}

{% block script %}
<script type="text/javascript">
jQuery(function($){
	$("#table_point").DataTable(
	    {
	        "paging"        : true,                 //페이징
	        "ordering"      : true,                 //컬럼 클릭 시 오더링을 적용
	        "info"          : true,                 //페이지 상태에대한 정보를 표시
	        "filter"        : true,                 //검색창
	        "lengthChange"  : true,                 //블록 단위 변경 기능
	        //"order"         : [[ 0, "desc" ]],      //기본 컬럼 정렬 설정
	        "scrollX"       : false,
	        "scrollY"       : false,
	        "scrollCollapse": false,
            "language": {
                "emptyTable": "계측기가 없습니다.",
                "lengthMenu": "계측기 _MENU_ 개씩 보기",
                "info": "계측기 수 : 현재 _START_ - _END_개 / 총_TOTAL_개",
                "infoEmpty": "계측기 없음",
                "infoFiltered": "( _MAX_건의 계측기에서 필터링됨 )",
                "search": "검색: ",
                "zeroRecords": "일치하는 계측기가 없습니다.",
                "loadingRecords": "로딩중...",
                "processing":     "잠시만 기다려 주세요...",
                "paginate": {
                    "next": "다음",
                    "previous": "이전"
                }
            },
	    }
	);
});
</script>
{% endblock %}

app/templates/point/point_real.html
{% extends 'base.html' %}
{% block content %}

<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">계측 데이터</h1>
</div>

<!-- 내용 시작 -->
<div class="card shadow mb-4">
    <!-- 내용 타이틀 -->
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary"><small>area1 > </small> Real-time Measuaring Data</h6>
    </div>

    <div class="card-body">
        <!-- 그래프 블록 -->
        <div class="chart-area table-bordered p-3" border="1" style="width:100%; height:600px" >
            <canvas id="myChart" ></canvas>
        </div>
    </div>
</div>

{% endblock %}

<!-- 그래프 js -->
{% block script %}
<script type='text/javascript'>

var canvas = document.getElementById('myChart');
var data = {
    labels: ["January", "February", "March", "April", "May", "June", "July"],
    datasets: [
        {
            label: "진동데이터",
            fill: false,
            lineTension: 0.2,
            backgroundColor: "rgba(75,192,192,0.4)",
            borderColor: "rgba(75,192,192,1)",
            borderWidth: 1,
            pointRadius: 1.3,
            borderCapStyle: 'butt',
            borderDash: [],
            borderDashOffset: 0.0,
            borderJoinStyle: 'miter',
            pointBorderColor: "rgba(75,192,192,1)",
            pointBackgroundColor: "#fff",
            pointBorderWidth: 1,
            pointHoverRadius: 5,
            pointHoverBackgroundColor: "rgba(75,192,192,1)",
            pointHoverBorderColor: "rgba(220,220,220,1)",
            pointHoverBorderWidth: 2,
            pointRadius: 5,
            pointHitRadius: 10,
            data: [65, 59, 80, 0, 56, 55, 40, 24, 58, 72, 81, 54, 24],
        }
    ]
};

var zero = 13;

function adddata(){
    var value = Math.floor((Math.random() * 100) + 1);;
    myLineChart.data.labels.push(zero);
    myLineChart.data.labels.splice(0, 1);
    myLineChart.data.datasets[0].data.splice(0, 1);
    console.log(myLineChart.data.datasets[0].data);
    myLineChart.data.datasets[0].data.push(value);
    myLineChart.update();
    zero++;
}

setInterval(function(){adddata();},1000);

var option = {
    responsive: true,   //auto size : true
    maintainAspectRatio: false, // false하면 그래프 사이즈 조절 가능
    showLines: true,
    scales: {
        yAxes: [
            {
                display: true,
                ticks:
                {
                    beginAtZero:true,
                    min: 0,
                    max: 100
                }
            }
        ]
    }
};

var myLineChart = Chart.Line(canvas,{data:data,options:option});

</script>
{% endblock %}